batch-size=1000
database-name=""
transfer-collections=[""]
watch-collections=[""]

[receiver]
  connection=""
  type="mongodb"
  region="local"
  access-key-id=""
  secret-access-key=""
  session-token=""

[sender]
  connection=""

[[mapping]]
  collection-name=""
  collection-map=""