batch-size=1000
database-name=""
transfer-collections=[""]
watch-collections=[""]

[receiver]
  connection=""
  type="mongodb"

[sender]
  connection=""

[[mapping]]
  collection-name=""
  collection-map=""