version: '3.7'

services:
  mongodb:
    image: mongo:6
    command: mongod --replSet rs0 
    restart: always
    ports:
      - ${MONGO_INITDB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./.docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./.docker/volumes/mongodb/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://host.docker.internal:${MONGO_INITDB_PORT}/${MONGO_INITDB_DATABASE}?directConnection=true
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:172.17.0.1"